[package]
name = "sd"
version = "0.6.4"
edition = "2018"
authors = ["Gregory <gregory.mkv@gmail.com>"]
description = "An intuitive find & replace CLI"
readme = "README.md"
keywords = ["sed", "find", "replace", "regex"]
license = "MIT"
homepage = "https://github.com/chmln/sd"
repository = "https://github.com/chmln/sd.git"
categories = ["command-line-utilities", "text-processing", "development-tools"]

[dependencies]
regex = "1.1.7"
structopt = "0.2.16"
rayon = "1.1.0"
unescape = "0.1.0"
memmap = "0.7.0"
tempfile = "3.0.8"

[build-dependencies]
structopt = "0.2.16"
man = "0.3.0"

[profile.release]
opt-level = 3
lto = true
debug = false
