[package]
name = "sd"
version = "0.3.0"
edition = "2018"
authors = ["Gregory <gregory.mkv@gmail.com>"]
description = "An intuitive find & replace CLI"
readme = "README.md"
keywords = ["sed", "find", "replace", "regex"]
license = "MIT"
homepage = "https://github.com/chmln/sd"
repository = "https://github.com/chmln/sd.git"
categories = ["command-line-utilities", "text-processing", "development-tools"]

[dependencies]
regex = "1.1.0"
unescape = "0.1.0"
structopt = "0.2.14"
atomic-write = "0.1.3"

[profile.release]
opt-level = 3
lto = true
debug = false
