[package]
name = "sd"
version = "0.6.5"
edition = "2018"
authors = ["Gregory <gregory.mkv@gmail.com>"]
description = "An intuitive find & replace CLI"
readme = "README.md"
keywords = ["sed", "find", "replace", "regex"]
license = "MIT"
homepage = "https://github.com/chmln/sd"
repository = "https://github.com/chmln/sd.git"
categories = ["command-line-utilities", "text-processing", "development-tools"]

[dependencies]
regex = "1.3.1"
structopt = "0.3.3"
rayon = "1.2.0"
unescape = "0.1.0"
memmap = "0.7.0"
tempfile = "3.1.0"
anyhow = "1.0.17"

[build-dependencies]
structopt = "0.3.3"
man = "0.3.0"

[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1
