[package]
name = "sd"
version = "0.5.0"
edition = "2018"
authors = ["Gregory <gregory.mkv@gmail.com>"]
description = "An intuitive find & replace CLI"
readme = "README.md"
keywords = ["sed", "find", "replace", "regex"]
license = "MIT"
homepage = "https://github.com/chmln/sd"
repository = "https://github.com/chmln/sd.git"
categories = ["command-line-utilities", "text-processing", "development-tools"]

[dependencies]
regex = "1.1.6"
structopt = "0.2.15"
rayon = "1.0.3"
regex-syntax = "0.6.6"
unescape = "0.1.0"
memmap = "0.7.0"
tempfile = "3.0.8"

[profile.release]
opt-level = 3
lto = true
debug = false
