version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly-slim

    steps:
      - checkout

      - restore_cache:
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

      - run:
          name: Test
          command: cargo check 

      - save_cache:
          paths:
            - "~/.cargo"
            - "./target"
            - /usr/local/cargo/registry
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

